title: MATRIX Dashboards
subtitle: "Decision and Collaboration Dashboards: an Inventory"
name: "Wiktor Gustafsson"
repository: "sva-se/matrix-dashboards"
url: "https://sva-se.github.io/MATRIX-dashboards/"
description: An inventory of dashboard development for One Health disease surveillance.
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
toc: true
classes: wide

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true