title: MATRIX Dashboards
description: An inventory of dashboard development for One Health disease surveillance.
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
